package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import java.util.Random;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;


public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: OK. Ne fonctionnait pas car pointait sur "null" donc ne renvoyait aucun résultat.
    return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: OK. Apres avoir tenté d'implémenter cette fonction, elle ne fonctionnait pas. Pourquoi ? Car le import java.util.Random; n'était pas déclaré en haut.
    users.add(User.random());
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: OK. On cherchait la fonction remove dans la class list permettant de supprimer  un objet
         users.remove(user);
    }
}
